apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-web-ingress
spec:
  rules:
  - host: "{{ .Values.jellyfinFQDN }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jellyfin-service
            port:
              number: 8096
  - host: "{{ .Values.shorthost }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jellyfin-service
            port:
              number: 8096

