apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfinconfig
  labels:
    type: local
spec:
  capacity:
    storage: "{{ .Values.configsize }}"
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "{{ .Values.hostconfigpath }}"

