apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfinmedia
  labels:
    type: local
spec:
  capacity:
    storage: "{{ .Values.mediasize }}"
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "{{ .Values.hostmediapath }}"

