apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-claim
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: jellyfinmedia
  resources:
    requests:
      storage: "{{ .Values.mediasize }}"
