apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-claim
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: jellyfinconfig
  resources:
    requests:
      storage: "{{ .Values.configsize }}"
